import os
import re
import sys

def amalgamate(input_file, output_file, include_dir):
    included = set()
    include_pattern = re.compile(r'^\s*#\s*include\s+"([^"]+)"', re.MULTILINE)

    def process_file(file_path):
        rel_path = os.path.relpath(file_path, include_dir)
        if rel_path in included:
            return f"/* skipping already included {rel_path} */\n"
        
        included.add(rel_path)
        
        with open(file_path, 'r') as f:
            content = f.read()

        def replace_include(match):
            inc_name = match.group(1)
            inc_path = os.path.join(include_dir, inc_name)
            if os.path.exists(inc_path):
                return f"\n/* begin {inc_name} */\n" + process_file(inc_path) + f"/* end {inc_name} */\n"
            return match.group(0)
        
        return include_pattern.sub(replace_include, content)

    result = "/* This file was generated by amalgamate.py */\n"
    result += process_file(input_file)
    
    with open(output_file, 'w') as f:
        f.write(result)

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python amalgamate.py <entry_header> <output_file> <include_dir>")
        sys.exit(1)
    
    amalgamate(sys.argv[1], sys.argv[2], sys.argv[3])
