#ifndef SCON_H
#define SCON_H 1

#include "closure.h"
#include "compile.h"
#include "core.h"
#include "disasm.h"
#include "eval.h"
#include "gc.h"
#include "handle.h"
#include "intrinsic.h"
#include "item.h"
#include "list.h"
#include "native.h"
#include "parse.h"
#include "stdlib.h"
#include "stdlib_assoc.h"
#include "stdlib_error.h"
#include "stdlib_higher_order.h"
#include "stdlib_introspection.h"
#include "stdlib_sequences.h"
#include "stdlib_string.h"
#include "stdlib_system.h"
#include "stdlib_math.h"
#include "stdlib_type_casting.h"
#include "stringify.h"
#include "error.h"

#if defined(SCON_INLINE) || defined(SCON_IMPL)
#include "atom_impl.h"
#include "char_impl.h"
#include "closure_impl.h"
#include "compile_impl.h"
#include "core_impl.h"
#include "disasm_impl.h"
#include "eval_impl.h"
#include "function_impl.h"
#include "gc_impl.h"
#include "handle_impl.h"
#include "intrinsic_impl.h"
#include "item_impl.h"
#include "list_impl.h"
#include "native_impl.h"
#include "parse_impl.h"
#include "stdlib_impl.h"
#include "stdlib_assoc_impl.h"
#include "stdlib_error_impl.h"
#include "stdlib_higher_order_impl.h"
#include "stdlib_introspection_impl.h"
#include "stdlib_sequences_impl.h"
#include "stdlib_string_impl.h"
#include "stdlib_system_impl.h"
#include "stdlib_math_impl.h"
#include "stdlib_type_casting_impl.h"
#include "stringify_impl.h"
#include "error_impl.h"
#endif

#endif
